name: Release

on:
  push:

jobs:
  release:
    name: Create release from manifest version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Compare current version with fetched latest release
        id: compare_versions
        run: |
          wget https://gist.githubusercontent.com/os-ia/0e0aef0f3f0e929f5699a95d91ab1f0d/raw/check_manifest_version.py
          python3 check_manifest_version.py ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.NEW_VERSION }}
          tag_name: ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
